from deppClassifier.components.data_ingestion import DataIngestion
from deppClassifier.components.prepare_base_model import PrepareBaseModel
from deppClassifier.components.prepare_callback import PrepareCallback
from deppClassifier.components.training import Training

